skills = [
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "FastAPI",
    "Django",
    "Flask",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "TensorFlow",
    "PyTorch",
    "Scikit-Learn",
    "Pandas",
    "NumPy",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "NLP",
    "LLMs",
    "OpenAI API",
    "Docker",
    "Git",
    "GitHub",
    "AWS",
    "Azure",
    "Power BI",
    "Excel",
    "Linux"
]